import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Mounir Nessim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <div className="container">
              <h3>Web Development Portfolio and Demo</h3>
              <p>This site is a sample of my work in Web Development, written using Next.js and deployed with Vercal.</p>
              <p>
                  All code can be found on my github.
              </p> 
              <a href="https://github.com/mmnessim/next-portfolio" target="_blank" rel="noreferrer">Repository</a> <br />
          </div>
      </main>
    </>
  )
}
